language: c
sudo: false

env:
  - LUA="lua5.1" LUAC="luac5.1"

addons:
  apt:
    packages:
      - lua5.1
      - luarocks
      - liblua5.1-bitop0

install:
  - eval $(luarocks path --bin)
  - luarocks install --local luaunit 2.1
  - luarocks install --local mockagne 1.0

script:
  - cd tests
  - ./lualint.sh
  - ./cs.sh
  - ./globals.sh
  - $LUA Items.lua

notifications:
  email:
    on_failure: always
    on_success: change

cache:
  apt: true
  directories:
    - $HOME/.luarocks
