language: erlang

env:
  - LUA="lua5.1" LUAC="luac5.1"

install:
  - sudo apt-get install $LUA luarocks
  - sudo luarocks install luaunit 2.1
  - sudo luarocks install mockagne 1.0
  - sudo luarocks install luabitop 1.0.2

script:
  - cd tests
  - ./lualint.sh
  - ./cs.sh
  - ./globals.sh
  - $LUA Items.lua

notifications:
  email:
    on_failure: always
    on_success: change
