language: c
sudo: false

env:
  - LUA="lua5.1" LUAC="luac5.1"

addons:
  apt:
    packages:
      - $LUA
      - luarocks

install:
  - eval $(luarocks path --bin)
  - luarocks install luaunit 2.1
  - luarocks install mockagne 1.0
  - luarocks install luabitop

script:
  - cd tests
  - ./lualint.sh
  - ./cs.sh
  - ./globals.sh
  - $LUA Items.lua

notifications:
  email:
    on_failure: always
    on_success: change

cache:
  apt: true
  directories:
    - $HOME/.luarocks
