name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Lua
        uses: leafo/gh-actions-lua@v6
        with:
          luaVersion: "5.1.5"
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v2
      - name: Install testing libraries
        run: |
          # luarocks install
          while read ROCK VERSION; do
            echo "::group::$ROCK"
            luarocks install --local $ROCK $VERSION
            echo '::endGroup::'
          done < .github/luarocks
      - name: Lint
        uses: nebularg/actions-luacheck@v1
        with:
          annotate: error
      - name: Test
        run: lua tests/Items.lua
      - name: Write libraries to .toc
        run: lua .release/libreplace.lua
      - name: Setup packager arguments
        id: packager-args
        if: github.base_ref || !startsWith(github.ref, 'refs/tags/')
        run: echo '::set-output name=args::-d'
      - name: Package and deploy
        uses: BigWigsMods/packager@cd13fb1
        with:
          args: ${{ steps.packager-args.outputs.args }}
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload packages to github
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: .release/AdiButtonAuras*.zip
